### PR TITLE
Fixed profile error on object & listing pages

### LINKED ISSUE #66: Object pages sometimes throw profile errors when opened in new tab
Initially found when clicking on resource results in catalog search, but can replicate when opening a new tab on any object page.

image

### PR DESCRIPTION
**Pull request by jamiefeiss**
Addressed an error on object & listing pages opened in a new tab caused by a race condition on retrieving profiles & saving in the Pinia store. Added a guard (a retry loop with a timeout of 10s) to requests on those pages to ensure that the profiles have been loaded in Pinia before firing off those requests. Resolves #66.

Also added a loading spinner component to those pages, as well as a small fix to the navbar.

### CODE REVIEW

File: src/views/PropTableView.vue [hunk 1]
```diff
@@ -441,32 +442,51 @@ onBeforeMount(() => {
...
+               
+        (function waitForProfiles() {
+            if (Object.keys(ui.profiles).length > 0) {
+                clearTimeout(expTimer)
+                return resolve()
+            };
+            setTimeout(waitForProfiles, 500);
+        })();
+    })
+}
```
Comment (edmondchuc) [inline src/views/PropTableView.vue:457]: Not a big deal but, possible to move to `src/util`?

Comment (edmondchuc) [reply src/views/PropTableView.vue:457]: It is defined in `ItemListView.vue` as well.

**Review by edmondchuc — COMMENTED** [review]
Quick question, is it possible to hoist the ensureProfiles checking to a common parent component?

File: src/views/PropTableView.vue (hunk 1 above)
Comment (jamiefeiss) [reply src/views/PropTableView.vue]: Done in latest commit

File: src/views/ItemListView.vue [hunk 2]
```diff
@@ -287,27 +289,30 @@ onBeforeMount(() => {
...
-        defaultProfile.value = ui.profiles[profiles.value.find(p => p.default)!.uri];
-        
-        // if specify mediatype, or profile is not default or alt, redirect to API
-        if ((route.query && route.query._profile) &&
-            (route.query._mediatype || ![defaultProfile.value.token, ALT_PROFILES_TOKEN].includes(route.query._profile as string))) {
-                window.location.replace(`${apiBaseUrl}${route.path}?_profile=${route.query._profile}${route.query._mediatype ? `&_mediatype=${route.query._mediatype}` : ""}`);
-        }
+    loading.value = true;
+    ensureProfiles().then(() => {
+        doRequest(`${apiBaseUrl}${route.fullPath}`, () => {
```
Comment (edmondchuc) [inline src/views/ItemListView.vue:294]: Would it make sense to call the ensureProfiles in App.vue? That way, the code that performs the checking is done in one place instead of having to do it within one of the view components.

File: src/views/PropTableView.vue [hunk 3]
```diff
@@ -442,31 +444,36 @@ onBeforeMount(() => {
...
-        
-        // if specify mediatype, or profile is not default or alt, redirect to API
-        if ((route.query && route.query._profile) &&
-            (route.query._mediatype || ![defaultProfile.value.token, ALT_PROFILES_TOKEN].includes(route.query._profile as string))) {
-                window.location.replace(`${apiBaseUrl}${route.path}?_profile=${route.query._profile}${route.query._mediatype ? `&_mediatype=${route.query._mediatype}` : ""}`);
-        }
+    loading.value = true;
+    // wait for profiles to be set in Pinia
+    ensureProfiles().then(() => {
+        console.log("profiles ready")
```
Comment (edmondchuc) [inline src/views/PropTableView.vue:450]: Same as above comment about performing the check in App.vue.

File: src/views/ItemListView.vue (hunk 2 above)
Comment (edmondchuc) [reply src/views/ItemListView.vue:294]: Resolving - side discussion needed to work out common pattern with accessing central store

**Review by edmondchuc — APPROVED** [review]
